### ISSUE TITLE
Invalid Partner Referral Code

### ISSUE THREAD

**Issue by thigarette** [opencampus-xyz/ocid-connect-js#13]
Are referral codes issued to partners by Open Campus? The docs say that the referral codes are "Unique identifiers assigned to partners for tracking during OCID account's registration". Kindly let us know, because whatever we define as the referral code in the sdk seems to be invalid when the user clicks on the check button. Of course it works when left blank but we wouldn't be able to prove that the OC ID registration was from us. Kindly assist.

![Screenshot from 2024-10-28 12-43-34](https://github.com/user-attachments/assets/17fcee3e-0f96-4ec2-a2b0-4d8c497b4219)

**Comment by jackycani** [comment]
hi @thigarette , currently only designated open campus partners would be given a partner referral code.
Each OCID is entitled to a set of one time use code as well, but they are less relevant for the purpose of OCID connect integration as they are not re-usable. 

If you are one of our OCX partners, please contact your opencampus ambassador regarding partner referral code. Thanks.
