### ISSUE TITLE
Redirect URI Not Allowed

### ISSUE THREAD

**Issue by thigarette** [opencampus-xyz/ocid-connect-js#17]
I had a question regarding the redirect URI. Our domain was whitelisted and we use a subdomain in our redirect URI e.g. `redirect.example.com` This was working just fine but we recently needed to switch the subdomain, e.g. `newredirect.example.com` and now get the "redirect uri not allowed" error when attempting the authentication flow.
![Screenshot from 2024-11-11 12-37-45](https://github.com/user-attachments/assets/6b9d33ef-afc5-4800-be61-f1b071c0cf3d)
I'm confused as to why this is the case since our whole domain, e.g. `example.com` was whitelisted once we filled the [App Whitelisting Form](https://forms.gle/g5JXqaJLCFkuznb57) Kindly advise.

_(I used `example.com` just for illustration purposes)_

**Comment by jackyquang** [comment]
we dont whitelist subdomains on top of the main domains to prevent users to abuse the system. If you need new subdomains to be whitelisted, please add them to the form @thigarette
